Bombfuse/emerald

Cargo.toml, src/core/engine.rs, src/core/error.rs, src/input/engine.rs, src/input/handler.rs, src/lib.rs, src/logging/engine.rs, src/rendering/engine.rs, src/rendering/handler.rs, src/rendering/texture.rs, src/world.rs, src/world/emerald_world.rs
This allows users to pick & choose which aspects of the engine they actually want.
For example, I may choose to implement my own physics and don't want bloat from Emerald.
=> Feature-ize physics, logging, and gamepads.

src/rendering/components/aseprite.rs, src/rendering/engine.rs
=> Add aseprite_update_system

Cargo.toml, README.md, examples/bunnymark.rs, examples/gamepads.rs, examples/labels.rs, src/assets/asset_loader.rs
Mostly based on miniquad source: https://github.com/not-fl3/miniquad/blob/4be5328760ff356494caf59cc853bcb395bce5d2/src/fs.rs
=> Asset loading on Android

Cargo.toml, examples/physics.rs, examples/physics_groups.rs, src/world/physics/engine.rs, src/world/physics/handler.rs
updating fontdue requires some core logic changes, avoiding it for now.
=> Update all dependencies except fontdue, because that would require work

.github/workflows/rust.yml, Cargo.toml, examples/gamepads.rs, examples/labels.rs, examples/mouse.rs, examples/physics.rs, examples/physics_groups.rs, src/assets/asset_loader.rs, src/core/components.rs, src/core/engine.rs, src/input.rs, src/input/button_state.rs, src/input/engine.rs, src/input/handler.rs, src/input/mouse_state.rs, src/world/physics/engine.rs, src/world/physics/handler.rs
BREAKING
Requires users to change `RigidBodyBuilder::new_kinematic()` to `RigidBodyBuilder::new_kinematic_position_based()` or `RigidBodyBuilder::new_kinematic_velocity_based()`.
Differences between the two can be found [here on rapier's page](https://rapier.rs/docs/user_guides/rust/rigid_bodies#rigid-body-type).
=> Merge master into dev, sync up history

Cargo.toml, examples/user_data.rs, src/assets/asset_store.rs, src/assets/writer.rs, src/core.rs, src/core/engine.rs
Create and get the user data directory for the app on Windows. Able to write files to the user directory.
=> Add user data directory for Windows. Saving to user files.

examples/audio.rs, examples/raycast.rs, examples/user_data.rs, src/assets/asset_store.rs, src/assets/writer.rs, src/audio/mixer.rs, src/audio/mixer/kira_backend.rs, src/core/error.rs, src/lib.rs, src/rendering/engine.rs, src/world/physics.rs, src/world/physics/engine.rs, src/world/physics/handler.rs, src/world/physics/types.rs
Add a `RayCastQuery` type that can return the first hit entity when passed into the physics handler.
=> Basic ray casting support for physics

examples/aseprite.rs, examples/audio.rs, examples/bunnymark.rs, examples/gamepads.rs, examples/hotreload.rs, examples/labels.rs, examples/logging.rs, examples/mouse.rs, examples/physics.rs, examples/physics_groups.rs, examples/raycast.rs, examples/render_to_texture.rs, examples/sprites.rs, examples/touch.rs, examples/user_data.rs, src/core/engine.rs, src/lib.rs
Because static dispatch is better than dynamic dispatch.
=> 📦 Unbox Game

src/types.rs
I assume here that the rectangle's y coordinate is the bottom, not the top, because +Y is up
=> Rectangle helpers

Cargo.toml, examples/physics.rs, examples/physics_groups.rs, examples/raycast.rs, examples/world_merging.rs, src/world/physics/engine.rs, src/world/physics/handler.rs, src/world/physics/handler_ref.rs
Breaking change
`RigidBodyBuilder::new_static()` -> `RigidBodyBuilder::fixed()`
=> BREAKING CHANGES: Update rapier version

Cargo.toml, src/rendering/engine.rs
=> Fix rendering + Version Bump

Cargo.toml
Fixes problem where build failed because miniquad removed version 0.3.10
=> Fix miniquad version

examples/sprites.rs
Demonstrate Sprite usage in a simple interactive manner - spawning and moving
=> Sprites example - spawn & move

.github/workflows/rust.yml, src/input/engine.rs, src/input/handler.rs, src/rendering/engine.rs, src/world.rs
This is the first commit to add some unit tests. Every new feature or feature rewrite should come with unit tests so we can guarantee certain behavior from the engine.
=> feat(testing): Add world unit testing

README.md, emerald/README.md
closeout https://github.com/Bombfuse/emerald/issues/81
=> Update readme #fix81

emerald/Cargo.toml, emerald/examples/bunnymark.rs, emerald/examples/camera.rs, emerald/src/rendering/rendering_engine.rs
Causing issues in game, but somehow didnt cause issues in any of the examples? weird
=> Fix counter

emerald/examples/window_manipulation.rs, emerald/src/core.rs, emerald/src/lib.rs
https://github.com/Bombfuse/emerald/issues/209
=> add set_cursor api

emerald/Cargo.toml, emerald/examples/assets/bunny.ent, emerald/src/rendering/components/label.rs, emerald/src/world/ent.rs, emerald/src/world/ent/ent_label_loader.rs
Can now load Label's from ent files
=> Add ent label loading

emerald/Cargo.toml, emerald/src/rendering/rendering_engine.rs, emerald/src/world/physics/physics_handler.rs
bug was causing sprites larger than the viewport not to render
=> Fix frustrum culling

emerald/Cargo.toml, emerald/src/rendering/rendering_engine.rs
=> fix(rendering): fix textured quad rendering

emerald/Cargo.toml, emerald/examples/assets/example.wrld, emerald/examples/autotilemap.rs, emerald/examples/tilemap.rs, emerald/src/core/components/autotilemap.rs, emerald/src/core/components/tilemap.rs, emerald/src/world/ent.rs
allows easy-ish autotilemap and ruleset definitions from files. opens up autotilemap creation for editors in the future
=> add autotile resource

emerald/src/core/components/autotilemap.rs, emerald/src/core/components/tilemap.rs, emerald/src/rendering/texture.rs
Able to load tileset resources from file, cleans up autotilemap/tilemap components in world files by sharing resources
=> Tileset resource

emerald/examples/physics.rs
=> Add missing parameter in physics.rs example
